#!/usr/bin/env bash
# Configuring my nginx server

apt-get update
apt-get install nginx -y
mkdir -p /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
    server_name _;
    location / {
        add_header X-Served-By \"\$HOSTNAME\";
        try_files \$uri \$uri/ =404;
    }
    location /redirect_me {
        return 301 https://twitter.com;
    }
    error_page 404 /404.html;
    location = /404.html {
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
