#!/usr/bin/env bash
# configures a new Ubuntu machine
# shellcheck disable=SC2154

# Install nginx on web-01 server
apt-get -y update
apt-get -y install nginx
mkdir -p /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html

# Create a custom 404 error page
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

# Write the Nginx server configuration
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
    server_name _;
    location / {
        add_header X-Served-By \"\$HOSTNAME\";
        try_files \$uri \$uri/ =404;
    }
    location /redirect_me {
        return 301 https://twitter.com;
    }
    error_page 404 /404.html;
    location = /404.html {
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

# Symlink to enable the site
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Test Nginx configuration for syntax errors
nginx -t

# Restart Nginx to apply the changes
service nginx restart
