#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend devslink
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 199820-web-01 54.210.78.58:80 check
    server 199820-web-02 52.86.177.174:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
