#!/usr/bin/env bash
# intaliing and configuring haproxy

apt-get -y update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.2
apt-get install -y haproxy=2.2.\*

echo "
frontend devslink.tech
    bind *:80
    default_backend web_backend

backend web_backend
    balance roundrobin
    server web-01 54.210.78.58:80 check
    server web-02 52.86.177.174:80 check
" > /etc/haproxy/haproxy.cfg

service haproxy restart
