#!/usr/bin/env bash
#shell script trying out the if statement

x=1
while [ $x -le 10 ]
do
    if [ $x -eq 9 ]
    then
        echo "Hi"
        x=$((x+1))
    else
        echo "Best School"
        x=$((x+1))
    fi
done
