#!/usr/bin/env bash
#shell script trying out the if statement

x=1
while [ $x -le 10 ]
do
    if [ $x -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    
    fi
    x=$((x+1))
done
