#!/usr/bin/env bash
#while loop if else

count=1

while [[ "$count" -le 10 ]]; do
	if [[ "$count" = 4 ]]; then
		echo "bad luck"
	elif [[ "$count" = 8 ]]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
