#!/usr/bin/env bash
# Trying out the case statement

x=1
max=20
while [ $x -le $max ]
do
    echo $x
    case $x in
        4)
            echo "bad luck from china"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
        ;;
    esac
    ((x++))
done

