#!/usr/bin/env bash
# Trying out the case statement

x=1
max=20
while [ $x -le $max ]
do
    case $x in
        4)
            echo "$x"
            echo "bad luck from china"
            x=$((x+1))
            ;;
        9)
            echo "$x"
            echo "bad luck from Japan"
            x=$((x+1))
            ;;
        17)
            echo "$x"
            echo "bad luck from Italy"
            x=$((x+1))
            ;;
        *)
        echo "$x"
        x=$((x+1))
        ;;
    esac
done

