#!/usr/bin/env bash
#A bash script that display time

Hour=0
while [ $Hour -le 12 ]
do
    echo "Hour: $Hour"
    minute=1
    while [ $minute -le 59 ]
    do
        echo "$minute"
        ((minute++))
    done
    ((Hour++))
done

